Wordsprocessing DocFormatProvider
telerik/document-processing-docs pull request #213
Opened 2021-04-23 16:16 UTC by velikovmartin

2021-04-26 08:48 UTC, TanyaDimitrova requested changes
You will need to also update:
- https://docs.telerik.com/devtools/document-processing/getting-started/getting-started
- https://docs.telerik.com/devtools/document-processing/introduction

2021-04-26 08:48 UTC, TanyaDimitrova commented on libraries/radwordsprocessing/cross-platform.md
> +If you need to import DOC files, you will need to refer the following assembly:
This section would be easier for the users to read if we add the information in a table

2021-04-26 08:48 UTC, TanyaDimitrova commented on libraries/radwordsprocessing/formats-and-conversion/word-file-formats/doc/doc.md
> +---
Remove this topic

2021-04-26 08:48 UTC, TanyaDimitrova commented on libraries/radwordsprocessing/formats-and-conversion/word-file-formats/doc/docformatprovider.md
> +**DocFormatProvider** makes it easy to import a **RadFlowDocument** from DOC format, preserving the entire document structure and formatting.
**DocFormatProvider** makes it easy to import a DOC file into a **RadFlowDocument**, preserving the entire document structure and formatting.

2021-04-26 08:48 UTC, TanyaDimitrova commented on libraries/radwordsprocessing/formats-and-conversion/word-file-formats/doc/docformatprovider.md
> +All you have to do in order to use **DocFormatProvider** is add references to the assemblies listed below:
To use **DocFormatProvider**, you should add references to the assemblies listed below:

2021-04-26 08:48 UTC, TanyaDimitrova commented on libraries/radwordsprocessing/formats-and-conversion/word-file-formats/doc/docformatprovider.md
> +In order to import a doc document, you need to use the **Import()** method of **DocFormatProvider**.
To import a DOC file, you should use the **Import()** method of **DocFormatProvider**.

2021-04-26 08:48 UTC, TanyaDimitrova commented on libraries/radwordsprocessing/formats-and-conversion/word-file-formats/doc/docformatprovider.md
> +The code in **Example 1** shows how to use **DocFormatProvider** to import a doc document from a file.
This sentence seems unnecessary. Maybe we can delete it?

2021-04-26 08:48 UTC, TanyaDimitrova commented on libraries/radwordsprocessing/formats-and-conversion/word-file-formats/doc/docformatprovider.md
> +And here is how you can import a document from byte array containing the doc document:
And here is how you can import a document from a byte array containing the document:
or
And here is how you can import a document from a byte array containing the .doc file:

2021-04-26 08:48 UTC, TanyaDimitrova commented on libraries/radwordsprocessing/formats-and-conversion/word-file-formats/docx/settings.md
> +description: This article describes the import/export settings which provide additional modification options
This article describes the settings that you can use to control how the DOCX documents are imported/exported in WordsProcessing.

2021-04-26 08:48 UTC, TanyaDimitrova commented on web.config
> +				<rule name="docx" enabled="true" stopProcessing="true">
Verify that works after merging it

2021-04-26 08:48 UTC, TanyaDimitrova commented on libraries/radwordsprocessing/formats-and-conversion/word-file-formats/doc/docformatprovider.md
> +DOT is а Word 97 - Word 2003 Binary file format, developed by Microsoft for representing document templates and is one of the supported formats by RadWordsProcessing.
Sounds pretty similar to the sentence above. Let's reword it

2021-04-26 08:48 UTC, TanyaDimitrova commented on libraries/radwordsprocessing/formats-and-conversion/word-file-formats/doc/docformatprovider.md
> +**DocFormatProvider** makes it easy to import a **RadFlowDocument** from DOC and DOT format, preserving the entire document structure and formatting.
**DocFormatProvider** makes it easy to import DOC or DOT files into a **RadFlowDocument**, preserving the entire document structure and formatting.

2021-04-26 08:48 UTC, TanyaDimitrova commented on libraries/radwordsprocessing/formats-and-conversion/word-file-formats/doc/docformatprovider.md
> +* Telerik.Windows.Documents.Flow.FormatProvider.Doc
Telerik.Windows.Documents.Flow.FormatProvider.Doc.dll

2021-04-26 08:48 UTC, TanyaDimitrova commented on libraries/radwordsprocessing/formats-and-conversion/word-file-formats/doc/docformatprovider.md
> +In order to import a DOC or DOT document, you need to use the **Import()** method of **DocFormatProvider**.
To import a DOC or DOT document, you should use the **Import()** method of **DocFormatProvider**.

2021-04-26 08:48 UTC, TanyaDimitrova commented on libraries/radwordsprocessing/formats-and-conversion/word-file-formats/docx/docxformatprovider.md
> +description: Import and Export to Docx File Format Using DocxFormatProvider
Learn how you can import and export documents from/to DOCX using WordsProcessing.

2021-04-26 10:19 UTC, merged

2022-06-19 02:59 UTC, johncosmos653 approved these changes