Working on Nested mail merge docs
telerik/document-processing-docs pull request #246
Opened 2021-12-20 14:09 UTC by DKaramfilov

2021-12-20 16:14 UTC, vladislav-todorov commented on libraries/radwordsprocessing/editing/mail-merge.md
> +The nested mail merge functionality is supported from R1 2022. It allows you to merge data sources that contain nested data. For example your business object can contain a list of other objects and t
```suggestion
The nested mail merge functionality is supported from R1 2022. It allows you to merge data sources that contain nested data. For example, your business object can contain a list of other objects and this functionality allows accessing the properties of the underlying objects. In order to use the underlying objects, you need to  declare a group. Currently, the following group tags are supported. 
```

2021-12-20 16:18 UTC, vladislav-todorov commented on libraries/radwordsprocessing/editing/mail-merge.md
> +Now you need to add the fields using the specific supported names. In this example we are adding the fields to the table an we will use the TableStart/TableEnd tags, but this is not mandatory and you
```suggestion
Now you need to add the fields using the specific supported names. In this example we are adding the fields to the table and we will use the TableStart/TableEnd tags, but this is not mandatory and you can use a tag of your choosing.
```

2021-12-20 16:20 UTC, vladislav-todorov commented on libraries/radwordsprocessing/editing/mail-merge.md
> +With the nested mail merge functionality it is possible to add all items to a single line. This is achieved by adding the group and regular fields to a single paragraph.
```suggestion
With the nested mail merge functionality, it is possible to add all items to a single line. This is achieved by adding the group and regular fields to a single paragraph.
```

2021-12-20 16:20 UTC, vladislav-todorov commented on libraries/radwordsprocessing/editing/mail-merge.md
> +>caption Figure 1: Mail Merging on single row and the results
```suggestion
>caption Figure 1: Mail Merging on a single row and the results
```

2021-12-20 16:21 UTC, vladislav-todorov commented on libraries/radwordsprocessing/editing/mail-merge.md
> +If you want separate the items on several rows you need to clowse the group on the next row
```suggestion
If you want to separate the items into several rows you need to close the group on the next row
```

2021-12-23 08:47 UTC, velikovmartin requested changes

2021-12-23 08:47 UTC, velikovmartin commented on libraries/radwordsprocessing/editing/mail-merge.md
> +Currently, all tags work equally and more than one option exist in order to improve the readability of the documents. The below example demonstrates how you can use the nested mail merge.
existS

2021-12-23 08:53 UTC, velikovmartin requested changes

2021-12-23 08:53 UTC, velikovmartin commented on libraries/radwordsprocessing/editing/mail-merge.md
> +	var editor = new RadFlowDocumentEditor(document);
There is additional tab here.

2021-12-23 08:59 UTC, DKaramfilov commented on libraries/radwordsprocessing/editing/mail-merge.md
> +Currently, all tags work equally and more than one option exist in order to improve the readability of the documents. The below example demonstrates how you can use the nested mail merge.
fixed

2021-12-23 09:00 UTC, DKaramfilov commented on libraries/radwordsprocessing/editing/mail-merge.md
> +	var editor = new RadFlowDocumentEditor(document);
fixed

2021-12-23 09:01 UTC, merged