Added sections for UserAccessPermissions, OwnerPassword, and an example code snippet that uses them. Changed ex.1's code snippet userPassword string variable to Us3rP4ssw0rd for clarity.
telerik/document-processing-docs pull request #259
Opened 2022-02-18 15:18 UTC by Svilen-Pavlov

Added sections for UserAccessPermissions, OwnerPassword, and an example code snippet that uses them. Changed ex.1's code snippet userPassword string variable to Us3rP4ssw0rd for clarity.

2022-02-18 15:31 UTC, TanyaDimitrova requested changes

2022-02-18 15:31 UTC, TanyaDimitrova commented on libraries/radpdfprocessing/formats-and-conversion/pdf/pdfformatprovider/settings.md
> +__Example 3__ shows how you can create a __PdfExportSettings__ object with a different set of settings. The settings used specify an OwnerPassword and UserAccessPermissions.
This example is specifically related to setting permissions. Move it just after the description for these permissions. Don't forget to update the numbering of the snippets

2022-02-18 15:31 UTC, TanyaDimitrova commented on libraries/radpdfprocessing/formats-and-conversion/pdf/pdfformatprovider/settings.md
> +{{region cs-radpdfprocessing-formats-and-conversion-pdf-settings_1}}
Leaving a blank line after the region opening tag makes the code snippet easier to read. Also make sure the code is formatted correctly.

2022-02-18 15:31 UTC, TanyaDimitrova commented on libraries/radpdfprocessing/formats-and-conversion/pdf/pdfformatprovider/settings.md
> +    // The following permissions are exported only if the settings.IsEncrypted property is set to true
This information should be also included in the description of UserAccessPermissions

2022-02-21 09:09 UTC, DKaramfilov approved these changes

2022-02-21 09:10 UTC, merged