added new conversion article
telerik/document-processing-docs pull request #264
Opened 2022-04-06 12:43 UTC by DKaramfilov

2022-04-06 12:53 UTC, Svilen-Pavlov requested changes
Typos on lines 14 & 15
"More infroamtion is availble here"

2022-04-11 11:46 UTC, TanyaDimitrova requested changes

2022-04-11 11:46 UTC, TanyaDimitrova commented on libraries/radpdfprocessing/formats-and-conversion/converting-other_formats.md
> + * __Converting Xlsx, Csv:__ Use the SpreadProcessing library. More information is availbel here:  [Using PdfFormatProvider]({%slug radspreadprocessing-formats-and-conversion-pdf-pdfformatprovider%})
- More information is available here
- Add all supported formats

2022-04-11 11:46 UTC, TanyaDimitrova commented on libraries/radpdfprocessing/formats-and-conversion/converting-other_formats.md
> + * __Converting Docx, Doc, RTF, and HTML:__ Use the WordsProcessing library. More infroamtion is availble here: [Formats and Convertion]({%slug radwordsprocessing-formats-and-conversion%}).
More information is available here:

2022-04-11 11:46 UTC, TanyaDimitrova commented on libraries/radpdfprocessing/formats-and-conversion/converting-other_formats.md
> +# Converting other formats to PDF
Convert from Other Formats to PDF

2022-04-11 12:50 UTC, merged