Add new KB - Creating TableCells with GoToAction and UriAction
telerik/document-processing-docs pull request #300
Opened 2022-12-08 09:00 UTC by mariaterzieva12

2022-12-08 10:08 UTC, DKaramfilov requested changes
It apers to be unfinished. Did you forget to save it?

2022-12-08 10:08 UTC, DKaramfilov commented on knowledge-base/creating-tablecells-with-gotoaction-and-uriaction.md
> +slug:
No Slug!

2022-12-08 10:08 UTC, DKaramfilov commented on knowledge-base/creating-tablecells-with-gotoaction-and-uriaction.md
> +The pdf format is different than the format in MS Word or other commonly used editors. With the PDF format, each content element has a specific position, and in some cases, each character is position
The first sentence does bring any value, can be removed. extend te description a bit more and describe the proposed solution.

2022-12-08 10:08 UTC, DKaramfilov commented on knowledge-base/creating-tablecells-with-gotoaction-and-uriaction.md
> +This article shows example of how you implement solution for inserting a widget.
The widget itself is not the purpose of the article in this case.

2022-12-08 10:08 UTC, DKaramfilov commented on knowledge-base/creating-tablecells-with-gotoaction-and-uriaction.md
> +## Table of Contents
We do not need TOC

2022-12-08 10:08 UTC, DKaramfilov commented on knowledge-base/creating-tablecells-with-gotoaction-and-uriaction.md
> +````C#
No regions for code. See other articles

2022-12-08 11:22 UTC, mariaterzieva12 commented
The comments are resolved with the new commit.

2022-12-09 15:14 UTC, TanyaDimitrova requested changes
It would be nice to include the component name first thing in the .md file name. This way, it would be easier to visually see at least the component in the list of KB files.

2022-12-09 15:14 UTC, TanyaDimitrova commented on knowledge-base/creating-tablecells-with-gotoaction-and-uriaction.md
> +tags: pdf, datatable, cells, widget
datatable and widget are not appropriate tags for this topic

2022-12-09 15:14 UTC, TanyaDimitrova commented on knowledge-base/creating-tablecells-with-gotoaction-and-uriaction.md
> +Although the editors do not allow you to insert the widgets it is possible to insert a place holder and then use its postion to insert the widget.
This line doesn't seem related to the topic

2022-12-12 12:08 UTC, mariaterzieva12 commented on knowledge-base/creating-tablecells-with-gotoaction-and-uriaction.md
> +description: This article demonstrates how can create table cells with GoTo action and UriAction in PDF document with Telerik Document Processing.
Done

2022-12-12 12:34 UTC, mariaterzieva12 commented
I have updated the requested changes.

2022-12-13 13:09 UTC, TanyaDimitrova requested changes
There are two identical files - one with the old name and one with the new one

2022-12-13 13:09 UTC, TanyaDimitrova commented on knowledge-base/pdfprocessing-creating-tablecells-with-gotoaction-and-uriaction.md
> +For this reason we use Action which defines the behaviour for an annotation. And annotation element associates an object with a location on a RadFixedPage.
I am still not sure I can understand why actions are needed and what this example shows from the description.

2022-12-13 13:24 UTC, mariaterzieva12 commented
the file with the old name is deleted

2022-12-20 12:15 UTC, merged